set(_CATKIN_CURRENT_PACKAGE "turtlebot")
set(turtlebot_VERSION "0.0.0")
set(turtlebot_MAINTAINER "kareem <kareem@todo.todo>")
set(turtlebot_PACKAGE_FORMAT "2")
set(turtlebot_BUILD_DEPENDS "gazebo" "geometry_msgs" "roscpp" "rospy" "rvis" "std_msgs" "tf" "urdf" "xacro")
set(turtlebot_BUILD_EXPORT_DEPENDS "gazebo" "geometry_msgs" "roscpp" "rospy" "rvis" "std_msgs" "tf" "urdf" "xacro")
set(turtlebot_BUILDTOOL_DEPENDS "catkin")
set(turtlebot_BUILDTOOL_EXPORT_DEPENDS )
set(turtlebot_EXEC_DEPENDS "gazebo" "geometry_msgs" "roscpp" "rospy" "rvis" "std_msgs" "tf" "urdf" "xacro")
set(turtlebot_RUN_DEPENDS "gazebo" "geometry_msgs" "roscpp" "rospy" "rvis" "std_msgs" "tf" "urdf" "xacro")
set(turtlebot_TEST_DEPENDS )
set(turtlebot_DOC_DEPENDS )
set(turtlebot_URL_WEBSITE "")
set(turtlebot_URL_BUGTRACKER "")
set(turtlebot_URL_REPOSITORY "")
set(turtlebot_DEPRECATED "")